### ISSUE TITLE
Add new Data-Structures and algorithms 

### ISSUE THREAD

**Issue by vinmaxx99** [Dark-Theme-Only/ds-algo#6]
Add new Data-Structures and algorithms which are not already present to this repo.

Do not cite this issue just create a new issue with the title as add "algo or ds name" and create pr for that issue

**Comment by aprilllllllll** [comment]
hello, I will implement data structure of Linked List.

**Comment by bharati-21** [comment]
@vinmaxx99  can we implement the data structure in any language of our choice? Or do you need the implementation in a specific language?

**Comment by vinmaxx99** [comment]
@bharati-21 Sure go Ahead and contribute in any language you like.

**Comment by deepanshu1999** [comment]
Successful Code submissions.
